[versions]
agp = "9.3.2"
kotlin = "2.3.21"
rtspServer = "1.4.3"
rootEncoder = "2.8.1"
junit = "4.13.2"
orgJson = "20250517"

[libraries]
rtsp-server = { module = "com.github.pedroSG94:RTSP-Server", version.ref = "rtspServer" }
rootencoder-library = { module = "com.github.pedroSG94.RootEncoder:library", version.ref = "rootEncoder" }
junit = { module = "junit:junit", version.ref = "junit" }
org-json = { module = "org.json:json", version.ref = "orgJson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
